### ISSUE TITLE
Nice job with the GUI

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [fs000x/ft260UI#1]
Hiya

Was looking through  your code at how you used the GUI.  I like what I see... you used lots of good parameters to make a GUI that is likely easy to use.  Stuff like focus, binding the return key make for a pleasant and more efficient user interface.  I also like the cleanup you do upon close and that you also did it without using an Exit button.  Shows you were paying attention while learning the SDK.

Would be great to see a screenshot sometime.  I know it's a simple GUI, but screenshots of simple stuff help other people that are developing simple user interfaces see that they are what people are using the package for.

Thanks for giving it a try.  👍

**Comment by fs000x** [comment]
Thanks for you suggestion. :smile:

**Comment by fs000x** [comment]
close this issue for commit(adf527e0babb02d9d037de7a50ce9c7a1f782c78)
